### ISSUE TITLE
Add KinD test verifying that the source deploys and becomes ready

### ISSUE THREAD

**Issue by Cali0707** [knative-extensions/eventing-ceph#474]
## Overview

We recently found that even though build and unit tests had been passing, the receive adapter panicked when it started when you actually deployed the ceph source. To address this, we should add a KinD test job that will:
1. Install eventing and the ceph source
2. Create a ceph source
3. Verify that the source becomes ready

## More info

These resources will likely be helpful while working on this:
- https://github.com/knative/eventing/blob/main/.github/workflows/kind-e2e.yaml
- https://github.com/knative-extensions/reconciler-test
- https://github.com/knative/eventing/tree/main/test/rekt

**Comment by swastik959** [comment]
hi @

**Comment by swastik959** [comment]
hi @Cali0707 I wanted to work on this issue and know how the ceph resource should look like . here is what I think it should look like : 
```
 apiVersion: sources.knative.dev/v1alpha1
kind: CephSource
metadata:
  name: test-ceph-source
spec:
  monitoringEndpoint: http://rook-ceph-mgr.rook-ceph.svc.cluster.local:9283/
  monitoringPort: 9283
  userName: admin
  userKey:
    name: rook-ceph-admin-secret
    key: ceph-secret
  topicName: knative-test-topic
  radarSink:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display 
```
